FROM python:3.10-slim

WORKDIR /app

# Copia arquivos necessários
COPY requirements-api.txt .
COPY setup.sh .
COPY src/ ./src/

# Torna o setup.sh executável
RUN chmod +x setup.sh

# Define a variável de ambiente para o setup.sh
ENV SERVICE=api

# Executa o setup.sh para configurar localidade e instalar dependências
RUN ./setup.sh

# Expõe a porta do FastAPI
EXPOSE 8000

# Comando para iniciar o servidor FastAPI
CMD ["uvicorn", "src.api.data_service:app", "--host", "0.0.0.0", "--port", "8000"]