FROM python:3.10-slim

WORKDIR /app

# Copia arquivos necessários
COPY requirements-web.txt .
COPY setup.sh .
COPY src/ ./src/
COPY assets/ ./assets/

ENV SERVICE=web

# Torna o setup.sh executável
RUN chmod +x setup.sh

# Executa o setup.sh para configurar localidade e instalar dependências
RUN ./setup.sh

# Expõe a porta do Dash
EXPOSE 8050

# Comando para iniciar o aplicativo Dash
CMD ["python", "src/eto_dashboard.py"]