version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: python src/eto_dashboard.py
    ports:
      - "8050:8050"
    depends_on:
      - redis
      - api
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      - LANG=pt_BR.UTF-8
    volumes:
      - ./src:/app/src
      - ./assets:/app/assets
      - ./logs:/app/logs

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      - LANG=pt_BR.UTF-8
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A src.eto_calculator worker --loglevel=info
    depends_on:
      - redis
      - api
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      - LANG=pt_BR.UTF-8
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  redis_data: